import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Button } from "../../src/components/Button/Button";
import { Input } from "../../src/components/Input/Input";

const ResetPassword: NextPage = () => {
  return (
    <div className="reset-password">
      <Head>
        <title>Reset Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="reset-password__section">
        <h1 className="reset-password__title">Reset Password</h1>
        <p className="reset-password__subtext">
          {" "}
          Enter a new password to proceed{" "}
        </p>

        <form>
          <div className="reset-password__form-input-section">
            <div className="reset-password__form-grid">
              <Input
                type="password"
                label="Password"
                placeholder="password"
                name="password"
                onChange={() => {}}
              />
            </div>
            <Input
              type="password"
              label="Confirm Password"
              placeholder="password"
              name="password"
              onChange={() => {}}
            />
          </div>
          <Button
            label="Reset Password"
            onClick={() => {}}
            className="reset-password__reset-password-btn"
            primary
            type="submit"
          />
        </form>
      </div>
    </div>
  );
};

export default ResetPassword;
