import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import Inbox from '../../public/svgs/employee-inbox.svg';
import { Button } from '../../src/components/Button/Button';
import BackIcon from '../../public/svgs/backicon.svg';

const AddEmployee: NextPage = () => {
  return (
    <div>
      <Head>
        <title>payroll-add-employee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="payroll-details-section">
        <div className=" payroll-details-section__payroll-details-settings">
          <div className=" payroll-details-section__back-icon">
            <Image src={BackIcon} alt="back-icon" />
            <div className="payroll-details-section__payroll-details-header">
              <p className="payroll-details-section__payroll-header">
                Payroll
                <span className="payroll-details-section__payroll-wallet">
                  (wallet balance ₦ 00)
                </span>
              </p>
            </div>
            <div className="employee-section__employee-inbox">
              <Image src={Inbox} alt="inbox icon" />
              <p>
                No details found.
                <br />
                Add employees to create payroll
              </p>
              <div className="payroll-details-section__add-employee-button">
                <Button
                  label={<>{'Add Employee'}</>}
                  onClick={() => {}}
                  className="employee-section__submit-btn"
                  primary
                  type="submit"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="payroll-details-section__add-employee-total-text">
        <p>Total</p>
      </div>
    </div>
  );
};

export default AddEmployee;
