import type { NextPage } from 'next';
import Head from 'next/head';


const NoPayroll: NextPage = () => {
  return (
    <div className="no-payroll">
      <Head>
        <title>payroll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          </Head>
          
    </div>
  );
}

export default NoPayroll;
