import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import DashboardLayout from '../../src/layouts/dashboard-layout/DashBoardLayout';
import { Button } from '../../src/components/Button/Button.component';
import Plus from '../../public/svgs/add-fill.svg';
import withAuth from 'src/helpers/HOC/withAuth';
import { PayrollTable } from '@/components/Table/payroll-table.component';

const PayrollDetails: NextPage = () => {
  return (
    <DashboardLayout pageTitle="Payroll">
      <div className="payroll-section">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className=" payroll-section__details">
          <div className="payroll-section__head">
            <h1 className="payroll-section__title">Payroll</h1>
            <div className="payroll-section__employee-button">
              <Button
                label={
                  <>
                    <Image src={Plus} alt="plus icon"></Image>{' '}
                    {'Create Payroll'}
                  </>
                }
                element="a"
                href="/payroll/create"
                className="payroll-section__submit-btn"
                primary
                type="submit"
              />
            </div>
          </div>
          <PayrollTable />
        </div>
      </div>
    </DashboardLayout>
  );
};

export default withAuth(PayrollDetails, ['Payroll', 'read']);
