import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import backicon from '../../public/svgs/backicon.svg';
import { Button } from '../../src/components/Button/Button';
import calendar from "../../public/svgs/Calendar.svg";

const PayrollSummary: NextPage = () => {
  return (
    <div className="payroll-summary">
      <Head>
        <title>payroll-summary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="payroll-summary__payroll-sidebar"></div>
      <main className="payroll-summary__payroll-main">
        <section className="payroll-summary__header-section">
          <Image src={backicon} alt="back-icon-image" />
          <div className="payroll-summary__btn-container">
            <Button
              label={<>{'Save Payroll'}</>}
              onClick={() => {}}
              className="payroll-summary__submit-btn"
              primary
              type="submit"
            />
          </div>
        </section>
        <section className="payroll-summary__section">
          <div className="payroll-summary__details">
            <div className="payroll-summary__payroll-summary">
              <h5 className="payroll-summary__summary-header">
                Summary{' '}
                <span className="payroll-summary__payroll-span-text">
                  (wallet balance ₦ 120,000)
                </span>{' '}
              </h5>
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-option">Payroll Size</p>
                <p className="payroll-summary__payroll-value">20</p>
              </div>{' '}
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-option">Unit Cost</p>
                <p className="payroll-summary__payroll-value">₦ 50</p>
              </div>{' '}
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-option">Total Bonuses</p>
                <p className="payroll-summary__payroll-value">₦ 500,000</p>
              </div>{' '}
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-option">Total Salary</p>
                <p className="payroll-summary__payroll-value">₦ 500,000</p>
              </div>{' '}
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-option">Total Net</p>
                <p className="payroll-summary__payroll-value">₦ 500,000</p>
              </div>{' '}
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-option">Total Texes</p>
                <p className="payroll-summary__payroll-value">₦ 500,000</p>
              </div>{' '}
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-option">
                  Other Deductions Total
                </p>
                <p className="payroll-summary__payroll-value">₦ 500,000</p>
              </div>{' '}
              <hr />
              <div className="payroll-summary__summary-options">
                <p className="payroll-summary__payroll-total-cost">
                  Total Payroll Cost
                </p>
                <p className="payroll-summary__payroll-total-amount">
                  ₦ 500,000
                </p>
              </div>
            </div>
          </div>

          <div className="payroll-summary__setpaydate">
            <h5 className="payroll-summary__setpaydate-title">Set Paydate</h5>
            <p className="payroll-summary__setpaydate-p">
              Enter date for salary to be disbursed
            </p>
            <hr />
            <div className="payroll-summary__setpay-calendar">
              <p className="payroll-summary__paydate">Pay Date</p>
              <div className="payroll-summary__calendar ">
                <p className="payroll-summary__date">10/8/2021</p>
                <Image
                  src={calendar}
                  alt="calendar-icon"
                  className="payroll-summary__calendar"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default PayrollSummary;
