import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import backicon from '../../public/svgs/backicon.svg';
import { Button } from '../../src/components/Button/Button';

const PayrollSummary: NextPage = () => {
  return (
    <div className="payroll-summary">
      <Head>
        <title>payroll-summary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="payroll-summary__header-section">
        <Image src={backicon} alt="back-icon-image" />
        <div className="payroll-summary__btn-container">
          <Button
            label={<>{'Save Payroll'}</>}
            onClick={() => {}}
            className="payroll-summary__submit-btn"
            primary
            type="submit"
          />
        </div>
      </section>
      <section className="payroll-summary__details">
        <div className="payroll-summary__payroll-summary">
          <h5>Summary (wallet balance ₦ 120,000) </h5>
          <hr />
          <div>
            <p>Payroll Size</p>
            <h5>20</h5>
          </div>{' '}
          <hr />
          <div>
            <p>Unit Cost</p>
            <h5>₦ 50</h5>
          </div>{' '}
          <hr />
          <div>
            <p>Total Bonuses</p>
            <h5>₦ 500,000</h5>
          </div>{' '}
          <hr />
          <div>
            <p>Total Salary</p>
            <h5>₦ 500,000</h5>
          </div>{' '}
          <hr />
          <div>
            <p>Total Net</p>
            <h5>₦ 500,000</h5>
          </div>{' '}
          <hr />
          <div>
            <p>Total Texes</p>
            <h5>₦ 500,000</h5>
          </div>{' '}
          <hr />
          <div>
            <p>Other Deductions Total</p>
            <h5>₦ 500,000</h5>
          </div>{' '}
          <hr />
          <div>
            <p>Total Payroll Cost</p>
            <h5>₦ 500,000</h5>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PayrollSummary;
