import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import backicon from '../../public/svgs/backicon.svg';
import { Button } from '../../src/components/Button/Button.component';
import editicon from '../../public/svgs/edit-icon.svg';

const PayrollDetails: NextPage = () => {
  return (
    <div className="payroll-details">
      <Head>
        <title>payroll-details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="payroll-details-section"></div>
      <div className="payroll-details-section__payroll-details-sidebar"></div>
      <section className="payroll-details__header-section">
        <Image
          src={backicon}
          alt="back-icon-image"
          className="payroll-details__back-icon"
        />
        <div className="payroll-details__title-container">
          <div>
            <h5 className="payroll-details__summary-header">
              Payroll{' '}
              <span className="payroll-details__payroll-span-text">
                (wallet balance ₦ 120,000)
              </span>{' '}
            </h5>
          </div>
          <Button
            label={<>{'Proceed'}</>}
            onClick={() => {}}
            className="payroll-details__proceed-btn"
            primary
            type="submit"
          />
        </div>
      </section>
      <table>
        <tr className="payroll-details__employeeTitle">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <th className="table-header">Name</th>
            </span>
          </span>
          <th className="table-header">Salary Amount (₦) </th>
          <th className="table-header">Net Amount (₦) </th>
          <th className="table-header">Bonus Amount (₦) </th>
          <th className="table-header">Amount Taxed (₦) </th>
          <th className="table-header">Pension Amount (₦) </th>
          <th className="table-header">Other Deductions (₦) </th>
        </tr>
        <tr className="payroll-details__employee">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <td>Name</td>
            </span>
          </span>
          <td>₦ 120,000 </td>
          <td>₦ 120,000 </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td className="payroll-details__edit-parent">
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>{' '}
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
        </tr>
        <tr className="payroll-details__employee">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <td>Name</td>
            </span>
          </span>
          <td>₦ 120,000 </td>
          <td>₦ 120,000 </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td className="payroll-details__edit-parent">
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>{' '}
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
        </tr>
        <tr className="payroll-details__employee">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <td>Name</td>
            </span>
          </span>
          <td>₦ 120,000 </td>
          <td>₦ 120,000 </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td className="payroll-details__edit-parent">
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>{' '}
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
        </tr>
        <tr className="payroll-details__employee">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <td>Name</td>
            </span>
          </span>
          <td>₦ 120,000 </td>
          <td>₦ 120,000 </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td className="payroll-details__edit-parent">
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>{' '}
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
        </tr>
        <tr className="payroll-details__employee">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <td>Name</td>
            </span>
          </span>
          <td>₦ 120,000 </td>
          <td>₦ 120,000 </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td className="payroll-details__edit-parent">
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>{' '}
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
        </tr>
        <tr className="payroll-details__employee">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <td>Name</td>
            </span>
          </span>
          <td>₦ 120,000 </td>
          <td>₦ 120,000 </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td className="payroll-details__edit-parent">
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>{' '}
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
        </tr>
        <tr className="payroll-details__employee">
          <span>
            <input
              type="checkbox"
              className="payroll-details__employee_Input"
              value="checkinputOne"
            />
            <span className="payroll-details__employee-name">
              {' '}
              <td>Name</td>
            </span>
          </span>
          <td>₦ 120,000 </td>
          <td>₦ 120,000 </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} alt="edit-icon" />
              </button>
            </span>
          </td>
          <td className="payroll-details__edit-parent">
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>{' '}
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
          <td>
            ₦ 120,000{' '}
            <span className="payroll-details__edit-icon">
              <button className="payroll-details__edit-icon-btn">
                <Image src={editicon} />
              </button>
            </span>
          </td>
        </tr>
      </table>
      {/* <hr /> */}
    </div>
  );
};

export default PayrollDetails;
