import type { NextPage } from "next";
import Head from "next/head";

const sidebar: NextPage = () => {
  return (
    <div>
      <div className="sidebar-section">
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <aside className="sidebar-section-table">
        </aside>
      </div>
    </div>
  );
};

export default sidebar;
