import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Button } from "../../components/Button/Button";
import { Input } from "../../components/Input/Input";

const EmailTemplate: NextPage = () => {
  return (
    <div className="email-template">
      <Head>
        <title>Email Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>Hi Kingsley,</p>
        <h1>Welcome to Sparkpay</h1>
      </div>
      <div>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam quis
          proin lobortis aliquet venenatis urna, senectus arcu ultrices.
          Volutpat, tempor mattis posuere tempor felis. Pulvinar dignissim nisi,
          sed sit in. Consequat enim risus sollicitudin, habitasse tortor
          habitant porttitor sagittis viverra dolor quis.
        </p>
        <p>Cheers, From Sparkpay Team</p>
      </div>
      <Button
        label="Get Started"
        onClick={() => {}}
        className="email-template__get-started-btn"
        primary
      />
    </div>
  );
};

export default EmailTemplate;
