import { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";
import hide from "../../public/Hide.svg";
import show from "../../public/Show.svg";
import { Button } from "../../components/Button/Button";
import { Input } from "../../components/Input/Input";

const Login: NextPage = () => {

  const [password, setPassword] = useState('');
  const [revealPassword, setRevealPassword] = useState(false);
  return (
    <div className="login-account">
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="login-account__section">
        <h1 className="login-account__title">Log In</h1>
        <p className="login-account__subtext">
          {" "}
          Enter your email & password to login{" "}
        </p>

        <form>
          <div className="login-account__form-input-section">
            <div className="login-account__form-grid">
              <Input
                type="email"
                label="Email Address"
                placeholder="Email Address"
                name="email"
              />
            </div>

            <Input
              type={revealPassword ? "text" : "password"}
              label="Password"
              placeholder="password"
              name="password"
              // value={password}
            />
            <Image
              src={hide}
              alt="hide password img"
              className="login-account__hide-and-show-password"
            />
          </div>
          <div className="login-account__forgot-password">
            <p className="login-account__forgot-password-title">
              Forgot Password?
            </p>
          </div>

          <Button
            label="Log In"
            onClick={() => {}}
            className="login-account__submit-btn"
            primary
          />
        </form>
        <div className="login-account__sign-up">
          <p className="login-account__sign-up-text">
            Don’t have an account?
            <span className="login-account__span-text"> Create Account</span>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
