import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { Button } from "../../components/Button/Button";
import { Input } from "../../components/Input/Input";

const Login: NextPage = () => {
  return (
    <div className="login-account">
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="login-account__section">
        <h1 className="login-account__title">Log In</h1>
        <p className="login-account__subtext">
          {" "}
          Enter your email & password to login{" "}
        </p>

        <form>
          <div className="login-account__form-input-section">
            <div className="login-account__form-grid">
              <Input
                type="email"
                label="Email Address"
                placeholder="Email Address"
                name="email"
              />
            </div>

            <Input
              type="password"
              label="Password"
              placeholder="password"
              name="password"
            />
          </div>
          <div className="login-account__forgot-password">
            <Link href="/forgot-password">
              <a className="login-account__forgot-password-title">
                Forgot Password?
              </a>
            </Link>
          </div>

          <Button
            label="Log In"
            onClick={() => {}}
            className="login-account__submit-btn"
            primary
          />
        </form>
        <div className="login-account__sign-up">
          <p className="login-account__sign-up-text">
            Don’t have an account?
            <Link href="/create-account">
              <a className="login-account__span-text"> Create Account</a>
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
