import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import BackIcon from '../../public/backicon.svg';

const EmployeeDetails: NextPage = () => {
  return (
    <div>
      <div className="employee-details">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className=" employee-details__employee-details-settings">
          <div className="employee-details__employee-details-header">
            <Image src={BackIcon} alt="back-icon" />
            <p className="employee-details__employee-header">
              Employees Details
            </p>
          </div>
          <button className="employee-details__employee-button">
            Edit Details
          </button>
        </div>
        <div className="employee-details__employee-settings-details">
          <div className="employee-details__employee-settings-flex">
            <div>
              <p>Name</p>
              <p>Esther Howard</p>
            </div>
            <div>
              <p>Email Address</p>
              <p>estherhoward@gmail.com</p>
            </div>
            <div>
              <p>Group</p>
              <p>Payroll group 1</p>
            </div>
            <div>
              <p>Dated Created</p>
              <p>July 20, 2021 </p>
            </div>
          </div>
          <div className="employee-details__employee-settings-flex1">
            <div>
              <p>Salary Amount</p>
              <p>₦ 210,000</p>
            </div>
            <div>
              <p>Payment Method</p>
              <p>Bank Account</p>
            </div>
            <div>
              <p>Bank Name</p>
              <p>First Bank Nigeria</p>
            </div>
            <div>
              <p>Account Number</p>
              <p>0033000099</p>
            </div>
          </div>
          <div className="employee-details__employee-settings-flex">
            <div>
              <p>Resident Country</p>
              <p>Nigeria</p>
            </div>
            <div>
              <p>Country Of Origin</p>
              <p>Nigeria</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EmployeeDetails;
