import React from 'react';
import Image from 'next/image';
import Head from 'next/head';
import info_icon from '../../public/svgs/info-icon.svg';
import avatar1 from '../../public/svgs/Avatar1.svg';
import avatar2 from '../../public/svgs/Avatar2.svg';
import avatar3 from '../../public/svgs/Avatar3.svg';
import avatar4 from '../../public/svgs/Avatar4.svg';

function EmployeeGroup() {
  return (
    <div className="employee-group">
      <Head>
        <title>Employee Group</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="employee-group__employee-group-cards">
        <div className="employee-group__section">
          <div className="employee-group__content">
            <div className="employee-group__group-title">
              <h5 className="employee-group__header-title">Group Name Here</h5>
              <Image
                src={info_icon}
                alt="group-employee-image"
                className="view-more-icon"
              />
            </div>
            <p className="employee-group__date-created-name">Date Created</p>
            <p className="employee-group__date-time-created">
              September 16, 2021 | 12:40 PM{' '}
            </p>
            <hr />
            <p className="employee-group__salary-title">Common Salary</p>
            <div className="employee-group__salary-amount-section">
              <p className="employee-group__salary-amount">₦ 200,000</p>
              <div className="employee-group__group-images">
                <Image
                  src={avatar1}
                  alt="group-employee-image"
                  className="employee-image"
                />
                <Image src={avatar2} alt="" className="employee-image" />
                <Image
                  src={avatar3}
                  alt="group-employee-image"
                  className="employee-image"
                />
                <Image
                  src={avatar4}
                  alt="group-employee-image"
                  className="employee-image"
                />
              </div>
            </div>
          </div>
        </div>

        <div className="employee-group__section">
          <div className="employee-group__content">
            <div className="employee-group__group-title">
              <h5 className="employee-group__header-title">Group Name Here</h5>
              <Image
                src={info_icon}
                alt="group-employee-image"
                className="view-more-icon"
              />
            </div>
            <p className="employee-group__date-created-name">Date Created</p>
            <p className="employee-group__date-time-created">
              September 16, 2021 | 12:40 PM{' '}
            </p>
            <hr />
            <p className="employee-group__salary-title">Common Salary</p>
            <div className="employee-group__salary-amount-section">
              <p className="employee-group__salary-amount">₦ 200,000</p>
              <div className="employee-group__group-images">
                <Image
                  src={avatar1}
                  alt="group-employee-image"
                  className="employee-image"
                />
                <Image src={avatar2} alt="" className="employee-image" />
                <Image
                  src={avatar3}
                  alt="group-employee-image"
                  className="employee-image"
                />
                <Image
                  src={avatar4}
                  alt="group-employee-image"
                  className="employee-image"
                />
              </div>
            </div>
          </div>
        </div>
        <div className="employee-group__section">
          <div className="employee-group__content">
            <div className="employee-group__group-title">
              <h5 className="employee-group__header-title">Group Name Here</h5>
              <Image
                src={info_icon}
                alt="group-employee-image"
                className="view-more-icon"
              />
            </div>
            <p className="employee-group__date-created-name">Date Created</p>
            <p className="employee-group__date-time-created">
              September 16, 2021 | 12:40 PM{' '}
            </p>
            <hr />
            <p className="employee-group__salary-title">Common Salary</p>
            <div className="employee-group__salary-amount-section">
              <p className="employee-group__salary-amount">₦ 200,000</p>
              <div className="employee-group__group-images">
                <Image
                  src={avatar1}
                  alt="group-employee-image"
                  className="employee-image"
                />
                <Image src={avatar2} alt="" className="employee-image" />
                <Image
                  src={avatar3}
                  alt="group-employee-image"
                  className="employee-image"
                />
                <Image
                  src={avatar4}
                  alt="group-employee-image"
                  className="employee-image"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default EmployeeGroup;
