import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import DashboardImage from "../../../dashboard-assets/OBJECTS.svg";
import Dropdown from "../../../dashboard-assets/dropdown.svg";
import PlusButton from "../../../dashboard-assets/plusbutton1.svg";
import { Button } from "../../../components/Button/Button";

const Table: NextPage = () => {
  return (
    <div className="dashboard-table">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dashboard-table__profile">
        <Image
          src={DashboardImage}
          className="dashboard-table__dashboardImage"
        />
        <Image src={Dropdown} />
      </div>
      <div className="dashboard-table__cards">
        <h1 className="dashboard-table__header">Dashboard</h1>
        <div className="dashboard-table__button">
          <Image src={ PlusButton}/>
          <Button
            label="Create Organisation"
            onClick={() => {}}
            className="dashboard-table__submit-btn"
            primary
          />
        </div>
      </div>
      <div className="dashboard-table__cardFlex">
        <div className="dashboard-table__cardDetails">
          <h1>0</h1>
          <p>Total number of Organisation</p>
        </div>
        <div className="dashboard-table__cardDetails">
          <h1>₦ 125,000</h1>
          <p>Total number of payroll burden</p>
        </div>
        <div className="dashboard-table__cardDetails">
          <h1>209</h1>
          <p>Total number of Payroll</p>
        </div>
        <div className="dashboard-table__cardDetails">
          <h1>5</h1>
          <p>Total number of employees</p>
        </div>
      </div>
    </div>
  );
};

export default Table;
