import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ProfileImage from "../../../dashboard-assets/profile.svg";
import Dropdown from "../../../dashboard-assets/dropdown.svg";

import { Button } from "../../../components/Button/Button";

const Table: NextPage = () => {
  return (
    <div className="dashboard-table">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dashboard-table__profile">
        
        <Image
          src={ProfileImage}
          className="dashboard-table__dashboardImage ml-5"
        />
        <Image src={Dropdown}/>
      </div>
      <div className="dashboard-table__head">
        <h1 className="dashboard-table__title">Dashboard</h1>
        <div className="dashboard-table__button">
          {/* <Image src={PlusButton} className="dashboard-table__createIcon" /> */}
          <Button
            label=" + Create Organisation"
            onClick={() => {}}
            className="dashboard-table__submit-btn"
            primary
          />
        </div>
      </div>
      <div className="dashboard-table__cardFlex">
        <div className="dashboard-table__cardDetails">
          <h1 className="dashboard-table__number">0</h1>
          <p className="dashboard-table__text">Total number of Organisation</p>
        </div>
        <div className="dashboard-table__cardDetails">
          <h1 className="dashboard-table__number">₦ 125,000</h1>
          <p className="dashboard-table__text">
            Total number of payroll burden
          </p>
        </div>
        <div className="dashboard-table__cardDetails">
          <h1 className="dashboard-table__number">209</h1>
          <p className="dashboard-table__text">Total number of Payroll</p>
        </div>
        <div className="dashboard-table__cardDetails">
          <h1 className="dashboard-table__number">5</h1>
          <p className="dashboard-table__text">Total number of employees</p>
        </div>
      </div>
    </div>
  );
};

export default Table;
