import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import DashboardImage from "../../../dashboard-assets/OBJECTS.svg";

const Table: NextPage = () => {
  return (
    <div>
      <div className="dashboard-table">
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="dashboard-table">
          <div>
            <Image src={DashboardImage}  className="dashboard-table __dashboardImage"/>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Table;
