import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ProfileImage from "../../dashboard-assets/profile.svg";
import Dropdown from "../../dashboard-assets/dropdown.svg";
import { Button } from "../../components/Button/Button";

const AddEmployee: NextPage = () => {
  return (
    <div>
      <div className="employee-section">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
            <div className="dashboard-table__profile">
              <Image
                src={ProfileImage}
                className="dashboard-table__dashboardImage ml-5"
              />
              <Image src={Dropdown} />
            </div>
            <div className="dashboard-table__head">
              <h1 className="dashboard-table__title">Employee</h1>
              <div className="dashboard-table__button">
                <Button
                  label=" + Add Employee"
                  onClick={() => {}}
                  className="employee-table__submit-btn"
                  primary
                />
              </div>
            </div>
          </div>
        </div>
  );
};

export default AddEmployee;
