import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "../../src/components/Button/Button";

const AddEmployee: NextPage = () => {
  return (
    <div>
      <div className="employee-section">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="employee-section__head">
          <h1 className="employee-section__title">Employee Settings</h1>
          
          <div className="employee-section__employee-button">
            <Button
              label=" Create Employee group"
              onClick={() => {}}
              className="employee-section__employee-button1"
              type="submit"
            />
            <Button
              label=" + Add Employee"
              onClick={() => {}}
              className="employee-table__submit-btn"
              primary
              type="submit"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default AddEmployee;
