import type { NextPage } from "next";
import Head from "next/head";


const employeeTableDetails: NextPage = ({Image,  Name, EmailAddress, Amount, Bank , Account, Date})=>{
  return (
    <div>
      <div className="employeeTableDetails">
        <Head>
          <title>EmployeeTableDetails</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div>
        <div>
          <Image src={ Image } />
          <p className="employeeTableDetails__name">{ Name}</p>
        </div>
        <div>
          <p>{ EmailAddress }</p>
          <p>{ Amount }</p>
          <p>{ Bank }</p>
          <p>{ Account }</p>
          <p>{ Date}</p>
        </div>
      </div>
    </div>
  );
};


export default employeeTableDetails;