import type { NextPage } from "next";
import Head from "next/head";
import EmployeeTableDetails from "./employeeTableDetails";
import Image from "next/image";

const employeeDetails: NextPage = () => {
  return (
    <div>
      <div className="employee-section">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <EmployeeTableDetails
            Image={ }
            Name={ "Tomike"}
            EmailAddress={"kolajoelizabeth@gmail.com"}
          />
        </div>
      </div>
    </div>
  );
};

export default employeeDetails;
