import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Button } from '../../src/components/Button/Button';
import DashboardLayout from '../../src/layouts/dashboard-layout/DashBoardLayout';
import withAuth from 'src/helpers/HOC/withAuth';
import SearchInput from '../../public/svgs/search.svg';
import Filter from '../../public/svgs/filter.svg';
import EmployeeInfo from '../../public/svgs/employeeIcon.svg';
import Inbox from '../../public/svgs/employee-inbox.svg';
import Plus from '../../public/svgs/add-fill.svg';

const Employee: NextPage = () => {
  return (
    <DashboardLayout>
      <div className="employee-section">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className=" employee-section__details">
          <div className="employee-section__head">
            <h1 className="employee-section__title">Employee Settings</h1>

            <div className="employee-section__employee-button">
              <Button
                label=" Create Employee group"
                onClick={() => {}}
                className="employee-section__employee-button1"
                type="submit"
              />
              <Button
                label={
                  <>
                    <Image src={Plus} alt="plus icon"></Image> {'Add Employee'}
                  </>
                }
                onClick={() => {}}
                className="employee-section__submit-btn"
                primary
                type="submit"
              />
            </div>
          </div>

          <div className="employee-section__employeeSearch">
            <div className="employee-section__employeeHeader">
              {/* <p>30 Employee(s)</p> */}
              <p>0 Employee(s)</p>
            </div>
            <div className="employee-section__searchInput">
              <div className="employee-section__searchIcon">
                <div>
                  <input
                    type="text"
                    placeholder="Search by name"
                    className="employee-section__search"
                  />
                </div>
                <div className="employee-section__searchImage">
                  <Image src={SearchInput} alt="search-image" />
                </div>
                <div className="employee-section__searchIcon">
                  <div>
                    <input
                      type="text"
                      placeholder="Filter"
                      className="employee-section__filter"
                    />
                  </div>
                  <div className="employee-section__searchImage">
                    <Image src={Filter} alt="filter-image" />
                  </div>
                  <span className="employee-section__employeeInfo">
                    <Image src={EmployeeInfo} alt="info-image" />
                  </span>
                </div>
              </div>
            </div>
          </div>

          <section>
            <table>
              <tr className="employee-section__employeeTitle">
                <span>
                  <input
                    type="checkbox"
                    className="employee-section__employee_Input"
                    value="checkinputOne"
                  />
                  <span className="employee-section__employee-name">
                    {' '}
                    <th>Name</th>
                  </span>
                </span>
                <th>Email Address</th>
                <th>Amount (₦) </th>
                <th>Payout Method</th>
                <th>Group</th>
                <th>Date Added</th>
              </tr>
            </table>

            <div className="employee-section__employee-inbox">
              <Image src={Inbox} alt="inbox icon" />
              <p>No employee yet</p>
            </div>

            <div className="employee-section__nextPages">
              <p>
                Showing <span className="employee">Page 1 of 10</span>
              </p>

              <div className="employee-section__prev_next_pages">
                <p>Prev</p>
                <p>1</p>
                <p>2</p>
                <p>Next</p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default withAuth(Employee);
