import type { NextPage } from "next";
import Head from "next/head";
import AddEmployee from "../employees/AddEmployee"
import SearchEmployee from "./SearchEmployee";
import EmployeeTableDetails from "./employeeTableDetails";


const Employee: NextPage = () => {
  return (
    <div>
      <div className="employee-section">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <div className=" employee-section__details">
            <AddEmployee />
            <SearchEmployee />
            <EmployeeTableDetails/>
          </div>
        </div>
      </div>
  );
};

export default Employee;
