import { EmployeeOnboardingForm } from '@/components/Employee/onboardingform.component';
import { EmployeeOnboarding } from '@/components/types';
import { FormikHelpers } from 'formik';
import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { toast } from 'react-toastify';
import { $api } from 'src/api';
import { HttpError } from 'src/api/repo/http.error';

const EmployeeOnboard: NextPage = () => {
  const router = useRouter();

  const token = (router.query.code as string) || ' ';

  const handleSugmit = async (
    values: EmployeeOnboarding,
    helpers: FormikHelpers<EmployeeOnboarding>,
  ) => {
    try {
      helpers.setSubmitting(true);
      await $api.employee.completeEmployeeOnboarding({
        token,
        ...values,
      });
      toast.success('onboarding successful');
      setTimeout(router.push, 1500, '/');
    } catch (error) {
      const err = error as HttpError;
      toast.error(err.message);
    } finally {
      helpers.setSubmitting(false);
    }
  };

  return (
    <div className="employee-onboard">
      <Head>
        <title>Employee Onboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="employee-onboard__section">
        <h1 className="employee-onboard__title">Employee Onboarding</h1>
        <p className="employee-onboard__subtext">
          {' '}
          Enter your details to complete your onboarding{' '}
        </p>
        <EmployeeOnboardingForm onSubmit={handleSugmit} />
        <div className="employee-onboard__sign-up">
          <p className="employee-onboard__sign-up-text">
            Please ensure your details are correct before submitting.
          </p>
        </div>
      </div>
    </div>
  );
};
export default EmployeeOnboard;
