import type { NextPage } from "next";
import Head from "next/head";
import SearchInput from "../../dashboard-assets/search.svg";
import Image from "next/image";

const SearchEmployee: NextPage = () => {
  return (
    <div>
      <div className="employee-section">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="employee-section">
          <div className="employee-section__searchFilter">
            <span>
              <p>12 employees</p>
            </span>
            <div>
              <input type="text" placeholder="Search by name" />
              <Image src={SearchInput}/>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SearchEmployee;
