import type { NextPage } from "next";
import Head from "next/head";
import SearchInput from "../../dashboard-assets/search.svg";
import Filter from "../../dashboard-assets/filter.svg";
import EmployeeInfo from "../../dashboard-assets/employeeIcon.svg";
import Image from "next/image";

const SearchEmployee: NextPage = () => {
  return (
    <div>
      <div className="employee-section">
        <Head>
          <title>Employee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="employee-section">
          <div className="employee-section__employeeSearch">
            <div>
              <p>12 employees</p>
            </div>
            <div className="employee-section__searchInput">
              <div>
                <Image
                  src={SearchInput}
                  className="employee-section__searchIcon"
                />
                <input
                  type="text"
                  placeholder="Search by name"
                  className="employee-section__search"
                />
              </div>
              <div>
                <input
                  type="text"
                  placeholder="Filter"
                  className="employee-section__filter"
                />
                <Image src={Filter} />
              </div>
              <span>
                <Image src={EmployeeInfo} />
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SearchEmployee;
