import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import Image from 'next/image';
import inbox from '../../public/svgs/letter.svg';

const CheckInbox: NextPage = () => {
  return (
    <div className="check-inbox">
      <Head>
        <title>Check Inbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="check-inbox__content">
        <h1 className="check-inbox__title">Check Your Inbox</h1>
        <p className="check-inbox__subtext">
          {' '}
          Password reset link has been sent to your inbox{' '}
        </p>
        <Image
          src={inbox}
          alt="Picture of the author"
          className="check-inbox__inbox-img"
        />
        <div>
          <p className="check-inbox__resend-now-subtext">Resend Now</p>
        </div>
      </div>
    </div>
  );
};

export default CheckInbox;
