import { NextPage } from "next";
import Head from "next/head";
import Navbar from "./Navbar";
import LandingPage from "./landing-page";
import Transaction from "./transaction";

const WaitList: NextPage = () =>
{
  return (
     <div className="wait-list-container">
      <Head>
        <title>Wait List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wait-list-container__landing-navbar">
        <Navbar />
        <LandingPage />
        </div>
        <div>
        <Transaction/>
        </div>
      </div>
  )
}

export default WaitList;