import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import DashboardImage from ".././../public/Dashboard.png";
import DashboardCheck from "../../public/Dashboardcheck.png";
import DashboardProfile from "../../public/DashboardProfile.png";
import greenHive from "../../public/greenhive.svg";
import orangeHive from "../../public/orangeHive.svg";
import DashboardcardInner from "../../public/cardInner.png";

const LandingPage: NextPage = () => {
  return (
    <div className="Landing-page-container">
      <Head>
        <title>Wait List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="Landing-page-container__wait-list-details">
        <h1 className="Landing-page-container__payroll-header">
          Payroll Made Easy
        </h1>
        <div className="Landing-page-container__payroll-greenhive">
          <Image src={greenHive} />
        </div>
        <p className="Landing-page-container__payroll-paragraph">
          Lorem ipsum dolor amet, consectetur adipiscing accumsan pellentesque
          volutpat.
        </p>
        <div></div>
        <input
          type="text"
          placeholder="Enter your email address"
          className="Landing-page-container__payroll-input"
        />
        <button className="Landing-page-container__wait-list-btn">Join Waitlist</button>
        <div className="Landing-page-container__payroll-orangehive">
          <Image src={orangeHive} />
        </div>
      </div>
      <div className="Landing-page-container__dashboard-image">
        <Image src={DashboardImage} />
      </div>
      <div className="Landing-page-container__dashboard-check">
        <Image src={DashboardCheck} />
      </div>
      <div className="Landing-page-container__dashboard-profile">
        <Image src={DashboardProfile} />
      </div>
      <div className="Landing-page-container__dashboard-card-inner">
        <Image src={DashboardcardInner} />
      </div>
    </div>
  );
};

export default LandingPage;
