import { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";

const Navbar: NextPage = () => {
  const [click, setClick] = useState(false);

  const handleClick = () => setClick(!click);
  const closeMobileMenu = () => setClick(false);

  return (
    <div className="wait-list-section">
      <Head>
        <title>Wait List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
            href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
            rel="stylesheet"
          /> */}
      </Head>
      <div>
        <nav className="wait-list-section__navbar-section">
          <a href="/" onClick={closeMobileMenu} className="wait-list-section__logo">
            <p>SparkPay</p>
          </a>
          {/* <div className="wait-list-section__line">
            <div className="wait-list-section__menu-icon" onClick={handleClick}>
              <i
                className={
                  click
                    ? "wait-list-section__fas fa-times "
                    : "wait-list-section__fas fa-bars"
                }
              />
            </div>
            <ul
              className={
                click
                  ? "wait-list-section__nav-menu active"
                  : "wait-list-section__nav-menu"
              }
            >
              <li className="wait-list-section__nav-item">
                <a
                  href="/"
                  className="wait-list-section__nav-links"
                  onClick={closeMobileMenu}
                >
                  About Us
                </a>
              </li>
              <li className="wait-list-section__nav-item">
                <a
                  href="/"
                  className="wait-list-section__nav-links"
                  onClick={closeMobileMenu}
                >
                  Invest
                </a>
              </li>

              <li className="wait-list-section__nav-item">
                <a
                  href="/faqs"
                  className="wait-list-section__nav-links"
                  onClick={closeMobileMenu}
                >
                  FAQ
                </a>
              </li>
              <div className="btn-cta">
                <a href="/signin">
                  <button className="wait-list-section__btn2">Login</button>
                </a>
              </div>
            </ul>
          </div> */}
        </nav>
      </div>
    </div>
  );
};

export default Navbar;
