import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import  payrollCheck from "../../public/payroll-check.svg"



const Transaction: NextPage = () =>
{
  return (
     <div className="transaction-container">
      <Head>
        <title>Transaction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
       <section>
         <h1>Focus on your business while we handle your Payroll.</h1>
         <p>Adipiscing tortor, pellentesque donec deaut accumsan nibh turpis pellentesque donec deaut consectetur.</p> 
          
         <div>
           {/* <Image src={payrollCheck} /> */}
         </div>
       </section>

      </div>
      </div>
  )
}

export default Transaction;