import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import removeicon from '../../public/svgs/remove-icon.svg';
import addicon from '../../public/svgs/add-icon.svg';
import backicon from '../../public/svgs/back-icon.svg';

const GroupDetails: NextPage = () =>{
  return (
    <div className="group-details">
      <Head>
        <title>Group Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="group-details__section">
        <div className="group-details__header-content">
          <div className="group-details__group-detail-title-section">
            <Image
              src={backicon}
              alt="group-details-image"
              className="view-more-icon"
            />
            <h5 className="group-details__group-detail-title">Group Details</h5>
          </div>
          <button className="group-details__edit-details-btn">
            Edit Details
          </button>
        </div>
        <div className="group-details__group-details-property">
          <div className="group-details__group-details-property-section">
            <div className="group-details__group-details-flex-body">
              <div className="">
                <p className="group-details__group-titles">Group Name</p>
                <p className="group-details__group-property-value">
                  Employee Group Name
                </p>
              </div>
              <div>
                <p className="group-details__group-titles">Common Salary</p>
                <p className="group-details__group-property-value">₦ 225,000</p>
              </div>
              <div>
                <p className="group-details__group-titles">Bonus</p>
                <p className="group-details__group-property-value">₦ 10,000</p>
              </div>
              <div>
                <p className="group-details__group-titles">Dated Created</p>
                <p className="group-details__group-property-value">
                  July 20, 2021{' '}
                </p>
              </div>
            </div>
            <hr />
            <div className="group-details__group-details-flex-body-inherit">
              <div>
                <p className="group-details__group-titles">
                  Staff of the month (Bonus)
                </p>
                <p className="group-details__group-property-value">₦ 10,000</p>
              </div>
              <div className="group-details__payroll-header">
                <p className="group-details__group-titles">
                  Payroll count (Bonus)
                </p>
                <p className="group-details__group-property-value">2</p>
              </div>
            </div>
          </div>

          {/* add employee section */}

          <div className="group-details__add-employee-container">
            <div className="group-details__add-employee-section">
              <div className="group-details__employee-header">
                <h6 className="group-details__employee-number">12 Employees</h6>
                <div className="group-details__add-employee-icon">
                  <Image
                    src={addicon}
                    alt="group-details-image"
                    className="add-icon"
                  />
                  <p className="group-details__add-employee-title">
                    Add Employee
                  </p>
                </div>
              </div>
              <div className="group-details__parent-container">
                <div className="group-details__user">
                  <p className="group-details__name">opeyemi</p>
                  <div className="group-details__image-container">
                    <Image
                      src={removeicon}
                      className="group-details__remove-icon"
                      alt="group-details-image"
                    />
                  </div>
                </div>
                <div className="group-details__user">
                  <p className="group-details__name">opeyemi</p>
                  <div className="group-details__image-container">
                    <Image
                      src={removeicon}
                      className="group-details__remove-icon"
                      alt="group-details-image"
                    />
                  </div>
                </div>{' '}
                <div className="group-details__user">
                  <p className="group-details__name">opeyemi</p>
                  <div className="group-details__image-container">
                    <Image
                      src={removeicon}
                      className="group-details__remove-icon"
                      alt="group-details-image"
                    />
                  </div>
                </div>
                <div className="group-details__user">
                  <p className="group-details__name">opeyemi</p>
                  <div className="group-details__image-container">
                    <Image
                      src={removeicon}
                      className="group-details__remove-icon"
                      alt="group-details-image"
                    />
                  </div>
                </div>{' '}
                <div className="group-details__user">
                  <p className="group-details__name">opeyemi</p>
                  <div className="group-details__image-container">
                    <Image
                      src={removeicon}
                      className="group-details__remove-icon"
                      alt="group-details-image"
                    />
                  </div>
                </div>{' '}
                <div className="group-details__user">
                  <p className="group-details__name">opeyemi</p>
                  <div className="group-details__image-container">
                    <Image
                      src={removeicon}
                      className="group-details__remove-icon"
                      alt="group-details-image"
                    />
                  </div>
                </div>{' '}
                <div className="group-details__user">
                  <p className="group-details__name">opeyemi</p>
                  <div className="group-details__image-container">
                    <Image
                      src={removeicon}
                      className="group-details__remove-icon"
                      alt="group-details-image"
                    />
                  </div>
                </div>{' '}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default GroupDetails;

