import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Button } from '../../src/components/Button/Button.component';
import { Input } from '../../src/components/Input/Input.component';
import { useAppSelector } from 'src/redux/hooks';
import { SelectInput } from '../../src/components/Input/seletct-input';
import { useRouter } from 'next/router';



const Login: NextPage = () => {
    const { user, countries } = useAppSelector((state) => state);
  const router = useRouter();

     if (user) {
       router.replace('/');
       return null;
     }

  return (
    <div className="login-account">
      <Head>
        <title>Employee Onboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="login-account__section">
        <h1 className="login-account__title">Employee Onboarding</h1>
        <p className="login-account__subtext">
          {' '}
          Enter your details to complete your onboarding{' '}
        </p>

        <form>
          <div className="login-account__form-input-section">
            <div className="login-account__form-grid">
              <SelectInput
                options={countries}
                displayValue="name"
                actualValue="id"
                name="country"
                // value={values.country}
                label="Country of Origin"
                // onChange={handleChange}
                // onBlur={handleBlur}
                // loading={!countries.length}
                // error={(touched.country && errors.country) || ''}
              />
              <SelectInput
                options={countries}
                displayValue="name"
                actualValue="id"
                name="country"
                // value={values.country}
                label="Country of Residence"
                // onChange={handleChange}
                // onBlur={handleBlur}
                // loading={!countries.length}
                // error={(touched.country && errors.country) || ''}
              />
              <Input
                type="email"
                label="Account Number"
                placeholder="account number"
                name="email"
                // onChange={}
              />
            </div>

            <Input
              type="password"
              label="Password"
              placeholder="password"
              //   onChange={handleChange}
              name="password"
            />
          </div>
          <Button
            label="Submit"
            type="submit"
            onClick={() => {}}
            className="login-account__submit-btn"
            primary
          />
        </form>
        <div className="login-account__sign-up">
          <p className="login-account__sign-up-text">
            Please ensure your details are correct before submitting.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
