import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { Button } from "../../components/Button/Button";
import { Input } from "../../components/Input/Input";

const ForgetPassword: NextPage = () => {
  return (
    <div className="forget-password">
      <Head>
        <title>Forget Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="forget-password__section">
        <h1 className="forget-password__title">Forget Password</h1>
        <p className="forget-password__subtext">
          Enter your email address to reset password
        </p>

        <form>
          <div className="forget-password__email-input">
            <Input
              type="email"
              label="Email Address"
              placeholder="Email Address"
              name="email"
            />
          </div>
          <Button
            label="Recover Password"
            onClick={() => {}}
            className="forget-password__recover-password-btn"
            primary
          />
        </form>
        <div>
          <Link href="/login">
            <a className="forget-password__go-back-login">Back to Log In</a>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default ForgetPassword;
