import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "./sidebar/sidebar";
import Table from "./table/table";

const Dashboard: NextPage = () => {
  return (
    <div>
      <div className="table-section">
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="table-section__dashboard">
          <Sidebar />
          <Table/>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
