import type { NextPage } from 'next';
// import Image from 'next/image';
import Head from 'next/head';
import { TableV2 } from '@/components/Table/Table.component';
import { TableLayout } from '@/components/Table/table-layout.component';
// import { EmployeeAddForm } from './../Form/employee-add.form';
import { KebabMenu } from '../KebabMenu/KebabMenu.component';


const EmployeeAddons: NextPage = () => {

  return (
    <div className="payroll-section">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TableLayout>
        <TableV2 className="payroll-create-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Salary</th>
              <th>Status</th>
              <th>Amount</th>
              <th>Payroll Cycle</th>
              <th>Frequency</th>
              <th>Addon Month</th>
              <th>type</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Abiodun Elijah</td>
              <td>#150,000</td>
              <td>Active</td>
              <td>Onetime</td>
              <td>Recurrent</td>
              <td>January</td>
              <td>Bonus</td>
              <td><span>
                Onetime
                    <KebabMenu
                      items={[
                        {
                          value: 'Edit',
                        },
                        {
                          value: 'Delete',
                        },
                      ]}
                    />
                    </span>
              </td>
            </tr>
          </tbody>
        </TableV2>
      </TableLayout>
    </div>
  );
};

export default EmployeeAddons;
