import type { NextPage } from 'next';
// import Image from 'next/image';
import Head from 'next/head';
import { TableV2 } from '@/components/Table/Table.component';
import { TableLayout } from '@/components/Table/table-layout.component';
// import { EmployeeAddForm } from './../Form/employee-add.form';

const EmployeeAddons: NextPage = () => {

  return (
    <div className="payroll-section">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TableLayout>
        <TableV2
          className="payroll-create-table"
        >
          <thead>
            <tr>
              <th>Name</th>
              <th>Salary </th>
              <th>Net Salary </th>
              <th>Payout Status</th>
            </tr>
          </thead>
          <tbody>
            

              return (
                <tr >
                  <td>
                  </td>
                  <td>
                  </td>
                  <td>
                  </td>
                 

                   
                  <td>
                   
                  </td>
                </tr>
              );
          </tbody>
        </TableV2>
      </TableLayout>
    </div>
  );
};

export default EmployeeAddons;
