import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Button } from '../../src/components/Button/Button';
import { Input } from '../../src/components/Input/Input';

const CreateAccount: NextPage = () => {
  return (
    <div className="create-account">
      <Head>
        <title>Create Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="create-account__content">
        <h1 className="create-account__title">Create Account</h1>
        <p className="create-account__subtext">
          Enter your details to create a free account
        </p>

        <form>
          <div className="create-account__form-input-area">
            <div className="create-account__form-grid">
              <Input
                type="text"
                label="First Name"
                placeholder="First Name"
                name="firstname"
                onChange={() => {}}
              />

              <Input
                type="text"
                label="Last Name"
                placeholder="Last Name"
                name="lastname"
              />
            </div>

            <Input
              type="email"
              label="Email Address"
              placeholder="Email Address"
              name="email"
            />

            <Input
              type="email"
              label="Country"
              placeholder="Country"
              name="country"
            />

            <Input
              type="password"
              label="Password"
              placeholder="password"
              name="password"
            />
          </div>

          <Button
            label="Create Account"
            onClick={() => {}}
            className="create-account__submit-btn"
            primary
          />
        </form>
        <div className="create-account__have-an-account-section">
          <p className="create-account__have-an-account-text">
            Already have an account?
            <span className="create-account__span-text"> Log In</span>
          </p>
          <p className="create-account__terms-and-conditions">
            By creating an account, you have agreed to our <br />{' '}
            <strong className="create-account__span-text underline-text">
              Terms
            </strong>{' '}
            and{' '}
            <strong className="create-account__span-text underline-text ">
              conditions
            </strong>
          </p>
        </div>
      </div>
    </div>
  );
};
export default CreateAccount;
