import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Button } from "../../components/Button/Button";
import { Input } from "../../components/Input/Input";

const ForgetPassword: NextPage = () => {
  return (
    <div className="forget-password">
      <Head>
        <title>Forget Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="forget-password__section">
        <h1 className="forget-password__title">Forget Password</h1>
        <p className="forget-password__subtext">
          {" "}
          Enter your email address to reset password{" "}
        </p>

        <form>
          <div className="login-account__form-input-section">
            <div className="login-account__form-grid">
              <Input
                type="email"
                label="Email Address"
                placeholder="Email Address"
                name="email"
              />
            </div>

            <Input
              type="password"
              label="Password"
              placeholder="password"
              name="password"
            />
          </div>
          <div className="login-account__forgot-password">
            <p className="login-account__forgot-password-title">
              Forgot Password?
            </p>
          </div>

          <Button
            label="Log In"
            onClick={() => {}}
            className="login-account__submit-btn"
            primary
          />
        </form>
        <div className="login-account__sign-up">
          <p className="login-account__sign-up-text">
            Don’t have an account?
            <span className="login-account__span-text"> Create Account</span>
          </p>
        </div>
      </div>
    </div>
  );
};

export default ForgetPassword;
